### ISSUE TITLE
repo: community.storage

### ISSUE THREAD

**Issue by ssbarnea** [ansible-collections/overview#155]
##### SUMMARY
I would like to request the community.storage namespace with the goal of making it a vendor agnostic solution for configuring shares on various storage devices, with primary goal to support NFS/SMB/iSCSI.

I emphasize the fact that this collection should aim to provide an unified interface via roles for creating these shares, regardless on which devices are supposed to create them.

Example of role use:
```yaml
- name: configure a share named foo accessible to guest
   community.storage.smb:
       name: foo
       type: public
       state: present  # optional, but it could be absent for removing a share (idempotent)
```

##### Name of collection
community.storage

##### GitHub maintainers
@ssbarnea
@gundalow
