### ISSUE TITLE
repo: cassandra

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#2]
##### Name of collection
cassandra

##### GitHub maintainers

@rhysmeister

**Comment by gundalow** [comment]
https://github.com/ansible-collections/cassandra/ has been created


- [ ] @rhysmeister to add content, see Grafana for an example
- [ ] Setup CI, I can use GitHub Actions if you'd like
-

**Comment by gundalow** [comment]
@rhysmeister is there anything else you need help with for Cassandra?

**Comment by rhysmeister** [comment]
@gundalow Dig into fixing the integration tests if you're keen... ;-)

No, all good I think but I go have a couple of general questions...

- Should we be using the new path syntax across the board? i.e. community.category.module
- Ansible Module Development Guidelines said to put shared code into lib/ansible/module_utils/ Are there any coding/style recommendations like this for collections?

**Comment by gundalow** [comment]
> * Should we be using the new path syntax across the board? i.e. community.category.module

Could you please expand on this a bit?

> * Ansible Module Development Guidelines said to put shared code into lib/ansible/module_utils/ Are there any coding/style recommendations like this for collections?
At a high level, the same guidelines apply as they did in ansible/ansible. You just need to be mindful that codes moved around, ie

ansible/ansible: ` lib/ansible/module_utils/ `
Collections: `plugins/module_utils/`

**Comment by rhysmeister** [comment]
@gundalow  If you remember the int tests for the mongodb lookup plugin weren't working. You advise using the following path community.mongodb.mongodb, i.e.

```
- name: "assert we complain properly if pymongo is not there"
  debug: msg="{{ lookup('community.mongodb.mongodb', mongodb_parameters ) }}"
  register: result
  ignore_errors: yes
```

This work but I note that I don't have to use this syntax in my module tests. i..e. I can still use the short form here, i.e.

```
- name: Create replicaset with members as dictionaries - mongodb_replicaset10
  mongodb_replicaset:
    login_host: localhost
    login_port: 3001
    login_database: admin
    replica_set: '{{ mongodb_replicaset10 }}'
    members:
    - host: "localhost:3001"
      priority: 1
    - host: "localhost:3002"
      priority: 1
    - host: "localhost:3003"
      priority: 0
      hidden: true
      slaveDelay: 3600
```

Should this be update to community.mongodb.mongodb_replicaset or can it be left as it is?
